name = "ai-video-tool"
main = "worker.js"
compatibility_date = "2026-09-08"
workers_dev = true
preview_urls = true

[assets]
directory = "./public"
binding = "ASSETS"

[vars]
TEST_BINDING = "GENZ_TEST"

[observability]
enabled = true
